### ISSUE TITLE
Add license to ws-1.py

### ISSUE THREAD

**Issue by nolanl** [Streetwalrus/dotfiles#3]
I have used your ws-1.py (thanks!) as a partial base for a more general append_layout replacement. I would like to contribute it to sway's contrib/ directory, so that others may benefit as well. I can't do that until I know the license you would like for your code, so that I may appropriately license the whole program.

Thanks,
- nolan

**Comment by 9ary** [comment]
Here you go, thanks for asking!
Please ping me when you submit it as well, I'd like to see what you've done.

**Comment by nolanl** [comment]
Wow, thanks for the fast response!

I will ping you when I submit.

**Comment by nolanl** [comment]
https://github.com/swaywm/sway/pull/6435
